### ISSUE TITLE
webpack should in the dependencies

### ISSUE THREAD

**Issue by yangxuanxing** [levp/wrapper-webpack-plugin#5]
In our project, we flatten all dependencies to the top node_modules folder.

![image](https://user-images.githubusercontent.com/3397523/49266944-243ac000-f493-11e8-9ee2-52a27f253985.png)

as webpack is not in the dependencies, when excute, it cannot resolve the webpack module

![image](https://user-images.githubusercontent.com/3397523/49266933-1be28500-f493-11e8-87fe-2b847a8cc21d.png)

**Comment by levp** [comment]
Looking at the most popular webpack plugins it seems that "most" of them have webpack as a peer dependency, unlike this plugin that doesn't have webpack listed anywhere in its dependencies (as of 2.0.0).

Having webpack as a peer dependency does seem like a reasonable thing to do, regardless of this particular issue.

@yangxuanxing Will having webpack listed in the `peerDependencies` of the `package.json` solve your problem?

**Comment by levp** [comment]
@yangxuanxing 

`webpack` have been added to `peerDependencies` in v2.1.0.

**Comment by yangxuanxing** [comment]
> Looking at the most popular webpack plugins it seems that "most" of them have webpack as a peer dependency, unlike this plugin that doesn't have webpack listed anywhere in its dependencies (as of 2.0.0).
> 
> Having webpack as a peer dependency does seem like a reasonable thing to do, regardless of this particular issue.
> 
> @yangxuanxing Will having webpack listed in the `peerDependencies` of the `package.json` solve your problem?

solved～ thanks for your work
